services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./test:/config
      - ./custom_components:/config/custom_components
      - ./tests/docker-overrides/const.py:/config/custom_components/ankermake/const.py
      - ./tests/docker-overrides/manifest.json:/config/custom_components/ankermake/manifest.json
    restart: unless-stopped
    environment:
      - TZ=Europe/Oslo
      - ANKERMAKE_DEBUG=true
    ports:
      - "8123:8123"