name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Get the latest tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Set version to the latest tag
        run: |
          sed -i "s/GITHUB_RELEASE_VERSION/${{ env.tag }}/g" custom_components/ankermake/manifest.json
          sed -i "s/GITHUB_RELEASE_VERSION/${{ env.tag }}/g" custom_components/ankermake/const.py
          
      - uses: "home-assistant/actions/hassfest@master"